[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Mitchell Hynes <me@mitchellhynes.com>"]
edition = "2018"

[[bin]]
name = "01"
path = "src/01/main.rs"

[[bin]]
name = "01_eb"
path = "src/01_eb/main.rs"

[dependencies]
