[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Mitchell Hynes <me@mitchellhynes.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
itertools = "0.9"
arrayvec = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
serde_scan = "0.4"
