[package]
name = "advent_of_code_2021"
version = "0.1.0"
authors = ["Mitchell Hynes <me@mitchellhynes.com>"]
edition = "2021"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
itertools = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_scan = "0.4"
